default:
  image: node:alpine
  before_script:
    - yarn install

stages:
  - code-quality
  - build
  - deploy

code-quality:
  inherit:
    default: true
  stage: code-quality
  script:
    - yarn check-quality
  only:
    - pushes
    - merge_requests

build:
  inherit:
    default: true
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - pushes
    - merge_requests

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk update && apk add rsync openssh
    - mkdir ~/.ssh
    - chmod 600 ~/.ssh
    - echo "$SSH_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
  resource_group: production
  script:
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete public/ $VPS_PATH
  only:
    - main
  when: manual
