default:
  image: node:alpine
  before_script:
    - yarn install

stages:
  - code-quality
  - build
  - deploy

code-quality:
  inherit:
    default: true
  stage: code-quality
  script:
    - yarn check-quality
  only:
    - pushes
    - merge_requests

build:
  inherit:
    default: true
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - pushes
    - merge_requests

deploy:
  stage: deploy
  script:
    - echo "deploy"
  only:
    - main
  when: manual